### ISSUE TITLE
Mod breaks other mods' in-game configuration functionality

### ISSUE THREAD

**Issue by floral-qua-floral** [Wyn-Price/Today-Is-A-Gift#1]
Today Is A Gift breaks the functionality of the in-game config menu for many other, unrelated mods. It seems to affect some, but not all, mods. Examples used in this issue report are Better With Mods and BetterFoliage, however others have been observed to be affected - [Nimble](https://www.curseforge.com/minecraft/mc-mods/Nimble), [Ice and Fire](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons), and even [Just Enough Items](https://www.curseforge.com/minecraft/mc-mods/jei). Some mods, including [Dynamic Surroundings](https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings), seem to be unaffected, however I have not tested it thoroughly.
I'm using Todayisagift 1.0.0 on Forge 1.12.2-14.23.5.2847.

How to reproduce (test 1, displays issues with restarting)
1. Install Today Is A Gift alongside [Better With Mods](https://www.curseforge.com/minecraft/mc-mods/bwm-suite)
2. Launch Minecraft, tweak any of BWM's config settings from the in-game Mods menu, and relaunch the game to apply the changes.
3. Observe that all settings have been reset to default.
At no point in the process does BWM's config file change, indicating that Today Is A Gift is somehow preventing the mods config from working at all.

How to reproduce (test 2, displays TIAG blocking config modification entirely)
1. Install Today Is A Gift alongside [Better Foliage](https://www.curseforge.com/minecraft/mc-mods/better-foliage) and its dependency [Forgelin](https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin)
2. Launch Minecraft and enter a world. Observe features such as rounded leaves and short grass.
3. Use BetterFoliage's in-game config keybind to open the configuration menu and change any setting - tweaking individuals or disabling the mod altogether will work fine for the test
4. Close BetterFoliage's config menu, and observe that the changes have not been applied - the world doesn't even re-render. This is not expected behavior, and if Today Is A Gift is not installed changes will be applied as soon as the menu closes.
5. Restart Minecraft and observe that all BetterFoliage settings have been reset to default.

I don't know if you're still looking after this mod, but if you are, a fix for this would be really lovely. I've been adding this mod to every pack I make and I've also been trying in vain to figure out what mod was breaking so many other mods' configs - I only discovered today that it's TIAG, which was pretty surprising. I'd love to be able to use this delightful little mod again. Thanks!

**Comment by Wyn-Price** [comment]
Should be fixed at [1.0.1](https://www.curseforge.com/minecraft/mc-mods/today-is-a-gift/files/2804523)
